version: "3.8"
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
    image: flask/distroless
    container_name: flask-distroless
    hostname: flask-dev-distroless
    ports: 
      - 8080:8080
    volumes:
       - ./app:/app
    # command: sleep 3600